<?php
$apps = new onCreateClass();
$dropDown = new phpFormComponents();
$dados = $this->getParameters();

?>
<script type="text/javascript">
    fn_setDadosLeiloeiro();
</script>
<div class="row">
    <div class="col-md-12">
    <form name="form-1" id="form-1" method="post" novalidate="novalidate">
    <input type="hidden" name="is_deleted" value="N">

    <div class="panel panel-primary">
        <div class="panel-heading">
            <!-- titulo do painel -->
            <div class="panel-title">
                <h4>
                    Novo Comitente
                    <br>
                    <small ><a > Adiciona um novo comitente</a></small>
                </h4>
            </div>

            <!-- Controle do painel -->
            <div class="panel-options ">

            </div>
        </div>
        <div class="panel-body">
            <div class="col-md-12"><div id="msg"></div></div>

            <div class="panel">

                <div class="row">

                    <div class="<?=$apps->getApplication()->getParam('srcid')? "col-md-6": "col-md-7";?>">
                        <label for="nome_comitente">Nome :</label>
                        <br />
                        <div class="form-group">
                            <input type="text" name="nome_comitente" id="nome_comitente" class="form-control"
                                   data-validate="required" data-message-required="Este campo é de preenchimento obrigatorio." placeholder="Campo Obrigatorio" value="<?=$dados->nome_comitente;?>">
                        </div>
                    </div>
                    <?php if($apps->getApplication()->getParam('srcid')){ ?>
                        <div class="col-md-2">
                            <label for="id_status">Situação:</label>
                            <br />
                            <div class="btn-group"  data-toggle="buttons-radio">
                                <button type="button"  class="btn <?=$dados->id_status == 1 ? "btn-default active": "btn-default";?>" onclick="fn_xjx_set_value('id_status', 1,'value');
                                    " data-toggle="button"><i class="icon-ok-sign"></i>&nbsp;Ativo
                                </button>
                                <button type="button" class="btn <?=$dados->id_status == 2 ? "btn-default active": "btn-default";?> " onclick="fn_xjx_set_value('id_status', 2,'value');" data-toggle="button"><i
                                        class="icon-remove-circle"></i>&nbsp;Inativo
                                </button>

                            </div>
                            <input type="hidden" name="id_status" id="id_status" value="<?=$dados->id_status == 2 ? 2: 1;?>">
                        </div>
                        <div class="col-md-3">
                            <label for="id_status">Natureza:</label>
                            <br />
                            <div class="btn-group"  data-toggle="buttons-radio">
                                <button type="button" id="pf"  class="btn <?=$dados->id_natureza == 1 ? "btn-default active": "btn-default";?>" onclick="fn_xjx_set_value('id_natureza', 1,'value');
                                    " data-toggle="button"><i class="icon-ok-sign"></i>&nbsp;Pessoa Fisíca
                                </button>
                                <button type="button" id="pj" class="btn <?=$dados->id_natureza == 2 ? "btn-default active": "btn-default";?> " onclick="fn_xjx_set_value('id_natureza', 2,'value');" data-toggle="button"><i
                                        class="icon-remove-circle"></i>&nbsp;Pessoa Juridica
                                </button>

                            </div>
                            <input type="hidden" name="id_natureza" id="id_natureza" value="<?=$dados->id_natureza == 2 ? 2: 1;?>">
                        </div>
                    <?php }else{ ?>
                        <div class="col-md-3">
                            <label for="id_status">Natureza:</label>
                            <br />
                            <div class="btn-group"  data-toggle="buttons-radio">
                                <button type="button" id="pf"  class="btn <?=$dados->id_natureza == 1 ? "btn-default active": "btn-default";?>" onclick="fn_xjx_set_value('id_natureza', 1,'value');
                                    " data-toggle="button"><i class="icon-ok-sign"></i>&nbsp;Pessoa Fisíca
                                </button>
                                <button type="button" id="pj" class="btn <?=$dados->id_natureza == 2 ? "btn-default active": "btn-default";?> " onclick="fn_xjx_set_value('id_natureza', 2,'value');" data-toggle="button"><i
                                        class="icon-remove-circle"></i>&nbsp;Pessoa Juridica
                                </button>

                            </div>
                            <input type="hidden" name="id_natureza" id="id_natureza" value="<?=$dados->id_natureza == 2 ? 2: 1;?>">
                        </div>
                        <input type="hidden" name="id_status" id="id_status" value="1">
                    <?php } ?>
                </div>
                <br />

                <!-- DOCUMENTOS -->
                <div class="row">
                    <div class="col-md-3">
                        <label for="cpf">CPF:</label>
                        <br />
                        <div class="form-group">
                            <input type="text" name="cpf" id="cpf" class="form-control"  onblur="fn_xjx_helperValidarDoc(xajax.getFormValues('form-1'),'cpf');"
                                   data-message-required="Este campo é de preenchimento obrigatorio." placeholder="Campo Obrigatorio" value="<?=$dados->cpf;?>">
                        </div>
                        <span id="span_cpf"></span>
                    </div>

                    <div class="col-md-3">
                        <label for="rg">RG:</label>
                        <br />
                        <input type="text" name="rg" id="rg" class="form-control" value="<?=$dados->rg;?>">
                    </div>

                </div>

                <br />

                <!--TELEFONES -->

                <div class="row">
                    <div class="col-md-1">
                        <label for="ddd_r">(DDD)</label>
                        <br />
                        <input type="text" name="ddd_r" id="ddd_r" class="form-control"  data-mask="999" value="<?=$dados->ddd_r;?>" >
                    </div>
                    <div class="col-md-2">
                        <label for="telefone_r">Telefone Res :</label>
                        <br />
                        <input type="text" name="telefone_r" id="telefone_r" class="form-control" data-mask="9999-9999" value="<?=$dados->telefone_r;?>">
                    </div>

                    <div class="col-md-1">
                        <label for="ddd_c">(DDD)</label>
                        <br />
                        <input type="text" name="ddd_c" id="ddd_c" class="form-control"  data-mask="999" value="<?=$dados->ddd_c;?>" >
                    </div>
                    <div class="col-md-2">
                        <label for="telefone_r">Telefone Com :</label>
                        <br />
                        <input type="text" name="telefone_c" id="telefone_c" class="form-control" data-mask="9999-9999" value="<?=$dados->telefone_r;?>">
                    </div>

                    <div class="col-md-1">
                        <label for="ddd_cel_1">(DDD)</label>
                        <br />
                        <input type="text" name="ddd_cel_1" id="ddd_cel_1" class="form-control"  data-mask="999" value="<?=$dados->ddd_cel_1;?>">
                    </div>
                    <div class="col-md-2">
                        <label for="telefone_c">Celular :</label>
                        <br />
                        <input type="text" name="celular_1" id="celular_1" class="form-control" data-mask="99999-9999" value="<?=$dados->celular_1;?>">
                    </div>
                </div>

                <!-- EMAIL -->
                <br />

                <div class="row">
                    <div class="col-md-6">
                        <label for="email_p">E-mail:</label>
                        <br />
                        <div class="form-group">
                            <input type="email" name="email_p" id="email_p" class="form-control" data-validate="required"
                                   data-message-required="Este campo é de preenchimento obrigatorio." placeholder="Campo Obrigatorio" value="<?=$dados->email_p;?>">
                        </div>
                    </div>

                </div>

                <br />

                <div class="row">
                    <div class="col-md-4">
                        <label for="contato">Nome do contato:</label>
                        <br />
                        <div class="form-group">
                            <input type="email" name="contato" id="contato" class="form-control" value="<?=$dados->contato;?>">
                        </div>
                    </div>
                    <div class="col-md-4">
                        <label for="contato">Forma de pagamento:</label>
                        <br />
                        <select id="id_forma_pagto" name="id_forma_pagto" class="form-control">
                            <?=$dropDown->DropDownList('tb_forma_pagto','id_forma_pagto','forma_nome',$dados->id_forma_pagto);?>
                        </select>
                    </div>

                </div>
            </div>

        </div>


    </div>

    <div class="panel panel-primary ">

        <div class="panel-heading">
            <!-- titulo do painel -->
            <div class="panel-title">
                <h4>
                    Dados de Endereço Residencial
                    <br>
                    <small>Endereços para o comitente</small>
                </h4>
            </div>
            <div class="panel-options">


            </div>

        </div>
        <div class="panel-body">

            <div class="row">

                <div class="col-md-3">
                    <label for="cep_r">CEP:</label>
                    <br/>
                    <input type="text" name="cep_r" onblur="fn_xjx_helperGetCep(xajax.getFormValues('form-1'), 'cep_r');" id="cep_r" class="form-control"
                           data-mask="99999-999" value="<?=$dados->cep_r;?>">
                </div>

                <div class="col-md-3">
                    <label for="id_logradouro_r">Logradouro:</label>
                    <br/>
                    <select name="id_logradouro_r" id="id_logradouro_r" class="form-control" value="<?=$dados->id_logradouro_r;?>">
                        <?php

                        $dropDown->DropDownList('tb_enderecos_logradouro', 'id_logradouro', 'logradouro_nome',$dados->id_logradouro_r);
                        ?>
                    </select>
                </div>


                <div class="col-md-3">
                    <label for="id_estado">Estado:</label>
                    <br/>
                    <select name="id_estado_r" id="id_estado_r" class="form-control">
                        <?php
                        $dropDown->DropDownList('tb_enderecos_estados', 'id_estado', 'estado_sigla',$dados->id_estado_r);
                        ?>
                    </select>
                </div>

            </div>

            <br/>

            <div class="row">
                <div class="col-md-5">
                    <label for="logradouro_nome_r">Endereço:</label>
                    <br/>
                    <input type="text" name="logradouro_nome_r" id="logradouro_nome_r" class="form-control" value="<?=$dados->logradouro_nome_r;?>">
                </div>
                <div class="col-md-1">
                    <label for="numero_r">Numero:</label>
                    <br/>
                    <input type="text" name="numero_r" id="numero_r" class="form-control" data-mask="99999" value="<?=$dados->numero_r;?>">
                </div>
                <div class="col-md-3">
                    <label for="complemento_r">Complemento:</label>
                    <br/>
                    <input type="text" name="complemento_r" id="complemento_r" class="form-control"  value="<?=$dados->complemento_r;?>">
                </div>

            </div>

            <br/>

            <div class="row">
                <div class="col-md-5">
                    <label for="bairro_r">Bairro:</label>
                    <br/>
                    <input type="text" name="bairro_r" id="bairro_r" class="form-control" value="<?=$dados->bairro_r;?>">
                </div>
                <div class="col-md-4">
                    <label for="cidade_r">Cidade:</label>
                    <br/>
                    <input type="text" name="cidade_r" id="cidade_r" class="form-control" value="<?=$dados->cidade_r;?>" >
                </div>


            </div>

        </div>


    </div>


    <div class="panel panel-primary">

        <div class="row">
            <div class="panel-body">

                <div class="col-md-2">
                    <button type="submit" class="btn btn-green btn-icon icon-left btn-block">
                        Salvar
                        <i class="entypo-check"></i>
                    </button>
                    <input type="hidden" name="<?= $apps->getApplication()->getParam('srcid') ? "Alterar" : "Salvar"; ?>" value=TRUE>
                </div>

                <div class="col-sm-2">
                    <button type="button" class="btn btn-orange btn-icon icon-left  btn-block" onclick="window.location='<?= $apps->getFunctions()->goToUrl("comitente",null); ?>'">
                        Cancelar
                        <i class="entypo-cancel"></i>
                    </button>
                </div>
            </div>
        </div>

    </div>




    </form>
    </div>

</div>